### ISSUE TITLE
is vue ?

### ISSUE THREAD

**Issue by smithyj** [jsilvermist/base-converter#1]
This is validate component with Vue framework?

**Comment by jsilvermist** [comment]
Unfortunately I'm not familiar with Vue, but looking at the getting started documentation I could at least write this **VERY** hacky example showing that at least the libraries are compatible.
http://plnkr.co/edit/fo0iDNobJAcOcCY1hytX

I found this project: https://github.com/karol-f/vue-custom-element

Not sure if that will help at all, but good luck!

**Comment by smithyj** [comment]
thank you
